/* This file is part of 34S.
 * 
 * 34S is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * 34S is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with 34S.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * 
 * This file is automatically generated.
 * Changes will not be preserved.
 */

#include "decNumber/decNumber.h"

const struct {
	int32_t digits;
	int32_t exponent;
	uint8_t bits;
	decNumberUnit lsu[151];
} const_2PI = {
	451,
	-450,
	0,
	{ 96, 237, 210, 586, 223, 865, 763, 234, 372, 184, 906, 183, 519, 731, 540, 114, 866, 218, 23, 883, 903, 293, 768, 42, 933, 640, 97, 61, 661, 22, 720, 180, 785, 735, 728, 430, 183, 508, 658, 925, 841, 41, 763, 349, 176, 631, 212, 13, 174, 449, 547, 282, 498, 520, 214, 787, 426, 296, 653, 908, 220, 697, 920, 846, 133, 297, 291, 818, 403, 542, 330, 566, 573, 467, 296, 951, 256, 892, 866, 331, 951, 621, 857, 928, 763, 860, 909, 897, 245, 289, 119, 211, 42, 877, 403, 205, 568, 900, 234, 962, 256, 816, 718, 450, 463, 164, 101, 219, 689, 187, 294, 613, 564, 26, 173, 296, 964, 135, 234, 684, 650, 69, 256, 997, 417, 572, 812, 632, 615, 184, 889, 949, 641, 211, 750, 798, 338, 394, 768, 5, 559, 766, 286, 925, 476, 586, 179, 307, 185, 283, 6 }
};

