/* This file is part of 34S.
 * 
 * 34S is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * 34S is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with 34S.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * 
 * This file is automatically generated.
 * Changes will not be preserved.
 */

#include "decNumber/decNumber.h"

const struct {
	int32_t digits;
	int32_t exponent;
	uint8_t bits;
	decNumberUnit lsu[13];
} const_gammaC15 = {
	39,
	-33,
	0,
	{ 288, 964, 551, 566, 456, 568, 476, 171, 129, 334, 930, 343, 593 }
};

