/* This file is part of 34S.
 * 
 * 34S is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * 34S is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with 34S.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * 
 * This file is automatically generated.
 * Changes will not be preserved.
 */

/* This file is for compiling user code */

#ifndef __USER_CONSTS_H__
#define __USER_CONSTS_H__

#define CONST_HALF (0)
#define CONST_PC_a (1)
#define CONST_PC_a0 (2)
#define CONST_PC_SM_luna (3)
#define CONST_PC_SM_terra (4)
#define CONST_PC_C (5)
#define CONST_PC_C1 (6)
#define CONST_PC_C2 (7)
#define CONST_PC_eV (8)
#define CONST_CNSTE (9)
#define CONST_PC_F (10)
#define CONST_PC_F_alpha (11)
#define CONST_PC_F_delta (12)
#define CONST_PC_g (13)
#define CONST_PC_G (14)
#define CONST_PC_Go (15)
#define CONST_PC_catalan (16)
#define CONST_PC_Ge (17)
#define CONST_PC_WGS_GM (18)
#define CONST_PC_PLANK (19)
#define CONST_PC_hon2PI (20)
#define CONST_PC_k (21)
#define CONST_PC_Jk (22)
#define CONST_PC_PlanckL (23)
#define CONST_PC_me (24)
#define CONST_PC_M_luna (25)
#define CONST_PC_mn (26)
#define CONST_PC_mp (27)
#define CONST_PC_PlanckM (28)
#define CONST_PC_mu (29)
#define CONST_PC_muc2 (30)
#define CONST_PC_mMu (31)
#define CONST_PC_M_sol (32)
#define CONST_PC_M_terra (33)
#define CONST_PC_Na (34)
#define CONST_NAN (35)
#define CONST_PC_atm (36)
#define CONST_PC_PlanckQ (37)
#define CONST_PC_R (38)
#define CONST_PC_Re (39)
#define CONST_PC_Rk (40)
#define CONST_PC_R_luna (41)
#define CONST_PC_Rinf (42)
#define CONST_PC_R_sol (43)
#define CONST_PC_R_terra (44)
#define CONST_PC_WGS_A (45)
#define CONST_PC_WGS_B (46)
#define CONST_PC_WGS_E2 (47)
#define CONST_PC_WGS_ES2 (48)
#define CONST_PC_WGS_F (49)
#define CONST_PC_t (50)
#define CONST_PC_tp (51)
#define CONST_PC_PlanckTh (52)
#define CONST_PC_Vm (53)
#define CONST_PC_Zo (54)
#define CONST_PC_alpha (55)
#define CONST_EULER (56)
#define CONST_PC_gamP (57)
#define CONST_PC_eps0 (58)
#define CONST_PC_lamC (59)
#define CONST_PC_lamCn (60)
#define CONST_PC_lamCp (61)
#define CONST_PC_mu0 (62)
#define CONST_PC_muB (63)
#define CONST_PC_muE (64)
#define CONST_PC_mun (65)
#define CONST_PC_muP (66)
#define CONST_PC_mu_u (67)
#define CONST_PC_mumu (68)
#define CONST_PC_sigma (69)
#define CONST_PHI (70)
#define CONST_PC_phi0 (71)
#define CONST_PC_WGS_OMEGA (72)
#define CONST_NEGINF (73)
#define CONST_INF (74)
#define CONST_ZERO (75)
#define CONST_ONE (76)
#define CONST_HIGH_RECIP_E (77)
#define CONST_LOW_RECIP_E (78)
#define CONST_RECIP_SQRT5 (79)
#define CONST_RECIP_SQRTPI (80)
#define CONST_POINT_2214 (81)
#define CONST_RECIPLN10 (82)
#define CONST_LN2 (83)
#define CONST_RECIPLN2 (84)
#define CONST_PI (85)
#define CONST_PIon2 (86)
#define CONST_SQRT_2_PI (87)
#define CONST_INT_R_BOUNDS (88)

#endif
